### PR TITLE
On server join, create a role named StressedOut

### PR DESCRIPTION
**Pull request by Vaibhav1808**
## Description

Adding a new feature in the bot which automatically assigns a role "StressedOut" to the newly joined member in the server.

## Issue Resolved

[Issue #4](https://github.com/armaanbadhan/Stress-Me-Out/issues/4)

## Checklist

Please make sure to review the following before submitting your PR: 

- [ ] I have read the code of conduct.
- [ ] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by armaanbadhan** [comment]
im sorry for the vague title of the issue, by on server join i meant when the bot joins a server it should create a role named "StressedOut", admins can assign this role to users, only users with this role(and admins ofc) can add and delete reminders. If youre still interested, comment on the issue ill assign you.

**Comment by Vaibhav1808** [comment]
I'll definitely give it a try, assign it to me

**Comment by armaanbadhan** [comment]
cool, can you comment on the issues thread once, not able to assign if you havent commented there once :)

**Comment by Vaibhav1808** [comment]
Done!

**Pull request merged**
